### ISSUE TITLE
renew.sh doesn't support a domain that only exists as a subdomain?

### ISSUE THREAD

**Issue by cjrobe** [galeone/letsencrypt-lighttpd#4]
I have an account at duckdns.org, so my domain is domain.duckdns.org (just an example).

When I edit the renew.sh file to say:

`domain_subdomains=( \
"duckdns.org domain" \
)`

The script runs but it then is running the validation on duckdns.org first, which causes the validation on domain.duckdns.org to never run.

When I change that to:

`domain_subdomains=( \
"domain.duckdns.org" \
)`

I get the error:
`renew.sh: line 26: domain_set[@]: unbound variable`

And line 26 in my file refers to:
`for sub_domain in "${domain_set[@]}"; do`

Thanks for any help.

**Comment by galeone** [comment]
Good catch! I should have fixed now. Let me know if it works

Thank you for using letsencrypt-lighttpd!

**Comment by cjrobe** [comment]
Wow, you are fast. Works great now, thanks :).
